apiVersion: v1
kind: Service
metadata:
  name: test-task
  labels:
    app: test-task
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8000
  selector:
    app: test-task
